on: 
  push:
    branches: 
      - master
name: Publish DootDoot Bot to Prod
jobs:
  Restart-App:
    name: Restart-App
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DH_PROD_FTP_HOST }}
        username: ${{ secrets.DH_PROD_FTP_USERNAME }}
        password: ${{ secrets.DH_PROD_FTP_PW }}
        port: 22
        script_stop: true
        script: |
            /home/robbiechatbot/doot-doot/DootRestart.sh
            echo "DootDoot successfully re-dooted!"
